### ISSUE TITLE
In linux and windows, Form Hint does not work properly

### ISSUE THREAD

**Issue by demosthenesk** [XusinboyBekchanov/VisualFBEditor#121]
In linux Form Hint, does not appear at all.
In Windows Form Hint, is set for the first time, but after that is not get updated by properties grid.
In Windows Form Hint, is set in code editor but not refreshed in properties grid.

**Comment by XusinboyBekchanov** [comment]
Fixed: Update Property Grid on change Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d3579dfa9cdb13fb4f16473909aa76a7b79cfbb4

**Comment by XusinboyBekchanov** [comment]
> In Windows Form Hint, is set for the first time, but after that is not get updated by properties grid.

Does this point also apply to the above fix?

**Comment by demosthenesk** [comment]
In linux update grid when code is changed in editor is ok. FIXED!
In Windows update grid is not fixed.

Also in linux Form Hint, does not appear at all.

**Comment by XusinboyBekchanov** [comment]
> In Windows update grid is not fixed.
Doesn't it work at all or does it work differently?

Fixed: Refresh Property Grid, If Selected Control is Design Control:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/1e96b5e60edd9b3c1ae1014e345e538ad6439204

**Comment by demosthenesk** [comment]
In linux, update grid is happening on changing view from Show Code, Show Form, Show Code and Form.

Feature request: A refresh button on properties tab that will refresh the grid by reading the code editor text

**Comment by demosthenesk** [comment]
In Windows, 
1) when i write a hint the first time is ok, it writes also in the code.
2) If i change the hint second time from grid, it does not change in code.
3) Also, if i change the hint from code the grid is not updated by changing view or save file

**Comment by demosthenesk** [comment]
Suggestion: Properties Grid should be updated after saving a file

**Comment by XusinboyBekchanov** [comment]
> In linux Form Hint, does not appear at all.

Fixed: Hint property Controls in Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4f766606c46858be8bc85ae15a2785bd563e2de9

**Comment by demosthenesk** [comment]
> > In linux Form Hint, does not appear at all.
> 
> Fixed: Hint property Controls in Linux:
> [XusinboyBekchanov/MyFbFramework@4f76660](https://github.com/XusinboyBekchanov/MyFbFramework/commit/4f766606c46858be8bc85ae15a2785bd563e2de9)

ok fixed in linux.

In Windows, properties grid does not update when code is changing or when file is saved.
In Windows on change property grid hint does not change code.

**Comment by XusinboyBekchanov** [comment]
>In Windows, properties grid does not update when code is changing or when file is saved.
Now usually updates when moving to another line.

> In Windows on change property grid hint does not change code.

Fixed: UString Resize:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9fad1b5ca9a11daf9fcf3cf5f7e6772543908b9a

**Comment by demosthenesk** [comment]
In Windows:
1) Add a Form
2) Click in designer the form
3) Set the Hint text. OK
4) Change the Hint from code and press enter. OK
5) Click on designer form
6) Try to set the hint again. FAILED!

**Comment by XusinboyBekchanov** [comment]
Fixed: Update Property Grid and Designer from Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/eaf5b5639ce27beded4bd766c0534d320aebb5b5

**Comment by XusinboyBekchanov** [comment]
> 4. Change the Hint from code and press enter. OK

Enter is not necessary, you can move to another line with the arrow key.

**Comment by demosthenesk** [comment]
In Windows,
1) add a form
2) click the form in designer and set hint from properties grid, write the text and press enter, OK
3) without change focus on properties grid, set again the hint text, Ok
4) edit code and change hint text from editor, change line OK
5) click form in designer
6) set hint from properties, in properties is changed, in code editor FAILED

**Comment by XusinboyBekchanov** [comment]
Here:

https://user-images.githubusercontent.com/32607344/131252355-748840b7-2098-461c-8da4-eb9a04eaf388.mp4

**Comment by demosthenesk** [comment]
Here is the strange behavior:
[20210829_170800.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/7072661/20210829_170800.zip)

**Comment by XusinboyBekchanov** [comment]
Fixed: Hint property of Code Editor:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/7aa2ec6231c33cc6e390de52b2315bd01c68f558

Fixed: Hint property of Control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/1bbed947429e05345616930b2f2b42b5d8ef49a7

**Comment by demosthenesk** [comment]
Finally fixed!
What a nasty bug...
Well all done!

**Comment by XusinboyBekchanov** [comment]
How was it so quickly checked?

**Comment by XusinboyBekchanov** [comment]
Thanks for this issue.

**Comment by demosthenesk** [comment]
> How was it so quickly checked?

yes in linux was ok
in windows checked and is fixed!
